# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoriaPost', models.CharField(max_length=50)),
                ('descripcionCategoriaPost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloPost', models.CharField(max_length=100)),
                ('contenidoPost', models.CharField(max_length=60000)),
                ('imagenPost', models.ImageField(upload_to='fotos/')),
                ('slugPost', models.SlugField()),
                ('fechaPubPost', models.DateField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.CategoriaPost')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('apellidoUsuario', models.CharField(max_length=20)),
                ('telefonoUsuario', models.CharField(max_length=20)),
                ('emailUsuario', models.EmailField(max_length=100)),
                ('creacionUsuario', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Usuario'),
        ),
    ]
