# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20170224_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAdopcion', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('edadAdopcion', models.IntegerField(help_text='Meses')),
                ('historiaAdopcion', models.TextField()),
                ('imagenAdopcion', models.ImageField(upload_to='fotos/adopcion/')),
                ('fechaPubAdopcion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Castrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obcionCastrado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoriaAdopcion', models.CharField(max_length=100)),
                ('descripcionCategoriaAdopcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRaza', models.CharField(max_length=100)),
                ('descripcionRaza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTamano', models.CharField(max_length=50)),
                ('descripcionTamano', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='castradoAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Castrado'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='categoriaAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.CategoriaAdopcion'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='colorAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Color'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='estadoAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Estado'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='razaAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Raza'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='tamanoAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Tamano'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='usuarioAdopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.Usuario'),
        ),
    ]
