# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_auto_20170309_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Region'),
        ),
        migrations.AddField(
            model_name='region',
            name='id_pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Pais'),
        ),
    ]
