# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_auto_20170309_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='id_ciudadAdopcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Ciudad'),
        ),
    ]
