# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0008_auto_20170309_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='id_estadoEvento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Estado'),
        ),
    ]
