# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0010_auto_20170314_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AddField(
            model_name='comedog',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AddField(
            model_name='post',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
    ]
