# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0012_auto_20170318_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AlterField(
            model_name='comedog',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id_estadoEvento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.EstadoEvento'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_aprobacion',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Aprobacion'),
        ),
    ]
