# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0014_auto_20170321_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='fotos/avatar/'),
        ),
    ]
