# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0017_auto_20170322_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugPost',
            field=models.SlugField(blank=True, default=models.CharField(max_length=100), null=True),
        ),
    ]
