# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0023_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='contenidoContacto',
            field=models.TextField(max_length=60000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='emailContacto',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombreContacto',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenidoPost',
            field=models.TextField(max_length=60000, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.CategoriaPost', verbose_name='Categoria de la Historia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagenPost',
            field=models.ImageField(blank=True, help_text='       Agregue una imagen relacionada a la historia si lo desea', null=True, upload_to='fotos/post/', verbose_name='Agregar Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tituloPost',
            field=models.CharField(max_length=100, verbose_name='Titulo de la Historia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videoPost',
            field=models.URLField(blank=True, help_text='Pegue en este campo la direccion URL del video que quiere agregar desde youtube', null=True, verbose_name='Agregar URL de un Video desde YouTube'),
        ),
    ]
